### ISSUE TITLE
The update script appends and doesn't remove old cert

### ISSUE THREAD

**Issue by antipopp** [bsyk/gcp-letsencrypt#3]
Hi! First of all thanks a lot for this script, it works perfectly.

I only have one question. I've noticed that the update script will append the old certificates to the freshly generated one. Is this on purpose? According to the readme you say it will remove the old certificate (not delete) from the LB but this is not the case. I'm a newbie to server infras and I don't know if there is any implication by leaving the old, expired certs running on the balancer.

If I'm correct I'll be happy to PR it.

**Comment by bsyk** [comment]
Hi @antipopp, thanks for creating this issue.

The script should be removing the old certificates from the LB when adding new ones for the same domain. If adding for a different domain, it will not remove the other ones.
I haven't run these scripts recently, so can't say whether they're working as intended.
@wsnel have you seen this issue?

If there's a clear code change needed to support removing the old certificates while renewing, please feel free to open a PR.

Thanks,
Ben

**Comment by antipopp** [comment]
Does the serial change at every renew? If it stays the same I think it is as you say. I raised the issue because I already had a LetsEncrypt cert on my LB that was named differently, and it was still there after using this script.

**Comment by bsyk** [comment]
The serial number should change with each renewal.
If you had a previous certificate that you manually created, it would likely only be removed if it were for the whole domain rather than a specific host. The regex match looks for certificates starting with the domain, not containing it.
Is/was this the case for you?

Note: if you run the script multiple times prior to certificate expiry, it won't generate a new certificate, it will reuse the existing un-expired one. This can make it difficult to test in a timely manner. You'll likely need to wait a week or so.
